#!/bin/sh
# executed from `.git/hooks/`

flutter format --set-exit-if-changed .

if [[ $? -ne 0 ]]; then
        echo "--- format failed"
        exit 1
fi

flutter analyze

if [[ $? -ne 0 ]]; then
        echo "--- analyze failed"
        exit 1
fi

#flutter test

#if [[ $? -ne 0 ]]; then
#        echo "--- tests failed"
#        exit 1
#fi

echo "git push is successful"
exit 0