#!/bin/sh
# execute from `.git/hooks/pre-commit`
# Make executable with `chmod +x`

declare -a filesToFormat="$(\
    git diff --cached --name-only --diff-filter=ACMR -z -- '*.dart'\
    | xargs -0 flutter format -n \
)"

flutter format "$filesToFormat"
git add "$filesToFormat"

echo " --- $filesToFormat: files formatted"

exit 0