#!/bin/sh
# execute from `.git/hooks/pre-commit`
# Make executable with `chmod +x`

declare -a files="$(\
    git diff --cached --name-only --diff-filter=ACMR -z -- '*.dart' | \
    xargs -0 flutter format\
)"

echo "All '*.dart' files formatted"

exit 0