name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^3.0.3
  bloc: ^1.0.0
  flutter_bloc: ^1.0.0
  meta: ^1.1.7
  equatable: ^0.6.1
  flutter_secure_storage: ^3.3.1+1
  flutter_form_builder: ^3.6.1
  json_annotation: ^3.0.0
  page_transition: ^1.1.5
  cached_network_image: ^1.1.2+1
  sqflite: ^1.1.7+1
  path: ^1.6.4
  path_provider: ^1.4.0
  flutter_cache_manager: ^1.1.3
  image: ^2.1.5
  camera: ^0.5.6+2
  video_player: ^0.10.2+5
  back_button_interceptor: ^4.1.1
  firebase_messaging: ^5.1.6
  google_maps_flutter: ^0.5.21+8
  geolocator: ^5.1.4+2
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.11
  flutter_facebook_login: ^3.0.0
  intl: ^0.15.8
  shared_preferences: ^0.5.4+3

dependency_overrides:
  intl: ^0.16.0 # Temporary for solve conflict with flutter_form_builder and flutter_localizations

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1
  json_serializable: ^3.2.3
  pedantic: ^1.8.0+1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Fira Sans
      fonts:
        - asset: assets/fonts/FiraSans-Regular.ttf
        - asset: assets/fonts/FiraSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/FiraSans-Light.ttf
          weight: 300
        - asset: assets/fonts/FiraSans-Italic.ttf
          style: italic
        - asset: assets/fonts/FiraSans-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/FiraSans-LightItalic.ttf
          style: italic
          weight: 300
